Metrics/LineLength:
  Max: 200

Metrics/MethodLength:
  Max: 20

Style/Documentation:
  Enabled: false

Style/GuardClause:
  Enabled: false

RegexpLiteral:
  Enabled: false

AllCops:
  Exclude:
    - db/schema.rb

